services:
  frontend:
    build: .
    ports:
      - 3000:3000
    environment:
      - VITE_API_URL=http://localhost:3333
    volumes:
      - .:/app
      - /app/node_modules

  json-server:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3333:3333
    command: ["yarn", "db:server"]